# Generated by Django 5.0.6 on 2024-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleO', models.CharField(max_length=300)),
                ('titleEn', models.CharField(max_length=300)),
                ('titleRu', models.CharField(max_length=300)),
                ('imdbID', models.CharField(max_length=30)),
                ('ratingIMDB', models.FloatField()),
                ('ratingKP', models.FloatField()),
                ('videoLocal', models.CharField(max_length=1000)),
                ('poster', models.CharField(max_length=1000)),
                ('posterLocal', models.CharField(max_length=1000)),
            ],
        ),
    ]
