# Generated by Django 5.0.6 on 2024-07-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonFilms', '0002_film_kid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='ratingIMDB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='ratingKP',
            field=models.FloatField(default=0),
        ),
    ]
